name: Build and Push Docker Image to Public ECR

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Login to Amazon ECR Public
              run: |
                  aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

            - name: Build Docker Image
              run: |
                  docker build -t julius/todo-app .

            - name: Tag Docker Image for Public ECR
              run: |
                  docker tag julius/todo-app:latest public.ecr.aws/a2e8v5y1/julius/todo-app:latest

            - name: Push Docker Image to ECR Public
              run: |
                  docker push public.ecr.aws/a2e8v5y1/julius/todo-app:latest

            - name: Get latest Task Definition ARN
              id: get-task-def
              run: |
                  TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition todo-app-td --query "taskDefinition.taskDefinitionArn" --region ${{ secrets.AWS_REGION }} --output text)
                  echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

            - name: Create appspec.yaml
              run: |
                  cat <<EOF > appspec.yaml
                  version: 0.0
                  Resources:
                    - TargetService:
                        Type: AWS::ECS::Service
                        Properties:
                            TaskDefinition: ${{ env.TASK_DEF_ARN }}
                            LoadBalancerInfo:
                                ContainerName: todo-app
                                ContainerPort: 3000
                  EOF

            - name: Upload appspec.yaml to S3
              run: |
                  aws s3 cp appspec.yaml s3://todoapp-appspec-bucket1/appspec.yaml

            - name: Trigger Blue-Green Deployment
              run: |
                  aws deploy create-deployment \
                  --application-name AppECS-todo-app-cluster-todo-service \
                  --deployment-group-name DgpECS-todo-app-cluster-todo-service \
                  --revision 'revisionType=S3,s3Location={bucket="todoapp-appspec-bucket1",key="appspec.yaml",bundleType="YAML"}' \
                  --region ${{ secrets.AWS_REGION }}
